### ISSUE TITLE
Check if user already has avatar

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#24]
When uploading an image and adding it to the user no check if the user might already have an avatar assigned is performed. This means that:
1. The User is assigned the avatar uploaded last.
2. Both attachments are still linked to the same user from the attachment side.
### How to reproduce

How does this even happen you might ask? Imagine a user with no avatar. Then you open two tabs with the Profile. And then upload avatars in both open tabs.
The assumption that one can't upload an avatar a second time because the Upload UI disappears after the first upload isn't valid if the UI was already loaded earlier. Also of course this needs to be properly handled server-side.
### Possible Solution

On upload check if the user already has an avatar assigned.
If yes then:
- delete the attachment
- or remove the link between avatar attachment and user from both ends
- or outright refuse to upload the second avatar

**Comment by kraftner** [comment]
@franz-josef-kaiser and me seem to agree that option 3, "outright refuse to upload the second avatar" is the way to go.

**Comment by franz-josef-kaiser** [comment]
As discussed in @kraftner office yesterday: 
- Outright deleting an attachment if another one is present is unexpected behavior. To make this a viable option, the plugin also would need to prompt the user if they really want to do this and possibly offer an "undo" step. This would make the process much more complicated as the attachment post would need to go into _trash_, which then depends on the config settings and it might not be clear to the user that setting zero trash days or deactivating revisions will not allow an "undo" step. The chance that the user will learn this by "try, fail, blame plugin author, never read docs" is high and too risky. Also there would need to be additional UI elements, etc. making the code even more complex with little to gain.
- Remove the link between avatar attachment and user from both ends: Currently the connection via IDs gets disconnected on only one end. @kraftner please clarify: the connection _"attachment⇒user"_ stays, but the user only has a single meta entry, correct? If so, then this actually is expected behavior and correct. I remember that I did this to make history of previous avatars/ logos possible. Maybe I just thought about – I am not completely sure. We might want to consider leaving it "as is", but make this behavior consistent and optional. Read: add a filter to _not_ delete attachments, add a ticket to allow the user to browse their history of previous avatars, like Gravatar allows to decide which avatar you want to use for which email-account. This should then go into a second issue.
- Outright refuse to upload the second avatar: This is what we decided now and the focus of this issue should stay with this. It is unexpected if you upload two avatars that you see your _old_ one in one tab, then reload and get presented a new one. Forcing the user to actively click the "trashbin"-icon in the upper right makes usage more clear. We might consider using the _Pointers API_ to tell the user where they have to click. [WP.SE answer from @Giuseppe-Mazzapica](http://wordpress.stackexchange.com/a/162794/385) on this topic.

**Comment by kraftner** [comment]
Concerning the second point:

> the connection "attachment⇒user" stays, but the user only has a single meta entry

Yes.

**Comment by franz-josef-kaiser** [comment]
Done with 30378c7 and c044b60
